import 'package:try_catch_exceptions/try_catch_exceptions.dart';
import 'package:test/test.dart';

void main() {
  test('calculate', () {
    expect(calculate(), 42);
  });
}
